use anchor_lang::prelude::*;


#[error_code]
pub enum AmmError {

    #[msg("Not enough liquidty generated by deposit")]
    NotEnoughLiquidity,

    #[msg("Not enough token balance")]
    NotEnoughTokenBalance,

    #[msg("Not enough LP token balance")]
    NotEnoughLPTokenBalance
}