use anchor_lang::prelude::*;


#[error_code]
pub enum AmmError {

    #[msg("Not enough liquidty generated by deposit")]
    NotEnoughLiquidity,

    #[msg("Not enough balance token balance")]
    NotEnoughTokenBalance,
}